### PR TITLE
remove schema and update justfile

### PR DESCRIPTION
**Pull request by arthur-cw**
retrieve from capybara-migrations instead
still lacking credentials cc @lmarangoni

### CODE REVIEW

**Comment by carneiro-cw** [comment]
I think this schema does not insert the special account with max balance

**Review by renancloudwalk — CHANGES_REQUESTED** [review]
needs to delete everything under the schema, there are 3 files there.
Also, needs to update the docker-compose commands in two places

**Comment by arthurmm-cloudwalk** [comment]
@arthur-cw is there any reason we can't let the schema in the repository ?

**Review by arthurmm-cloudwalk — CHANGES_REQUESTED** [review]
I don't see a reason for the schema to be outside the repository. Is there any reason ?

**Comment by renancloudwalk** [comment]
> I don't see a reason for the schema to be outside the repository. Is there any reason ?

It will conflict with capybara-migrations schema

**Pull request closed without merging**
