### PR TITLE
chore: add 0 to left of months, days and hours with only 1 digit

### PR DESCRIPTION
**Pull request by carneiro-cw**
### **PR Type**
Enhancement

___

### **Description**
- Enhanced the formatting of date and time components in file paths and names
- Added leading zeros to months, days, and hours that have only one digit
- Ensures consistent file naming and folder structure for better organization and sorting
- Affects the `historic_events_processor.rs` file in the `src/bin` directory

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>historic_events_processor.rs</strong><dd><code>Add leading zeros to date and time components</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/bin/historic_events_processor.rs

<li>Modified the folder path formatting to include leading zeros for month <br>and day<br> <li> Updated the file name formatting to include leading zeros for hour<br>

</details>

  </td>
  <td><a href="https://github.com/cloudwalk/stratus/pull/1849/files#diff-783a0df733dbcaeda4ed1c0f489555965746b725684709eab41c3c5992832f79">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by marcospb19-cw — APPROVED** [review]

**Comment by gabriel-aranha-cw** [comment]
Final benchmark completed with run ID: bench-3418316999

Benchmark Plot

**Comment by gabriel-aranha-cw** [comment]
Final benchmark completed with run ID: bench-305536981

Benchmark Plot

**Comment by gabriel-aranha-cw** [comment]
Final benchmark completed with run ID: bench-2554101325

Benchmark Plot

**Comment by gabriel-aranha-cw** [comment]
Final benchmark:
RPS Stats: Max: 940.00, Min: 754.00, Avg: 841.66, StdDev: 25.12
TPS Stats: Max: 940.00, Min: 754.00, Avg: 841.33, StdDev: 25.35
Plot: [View Plot](https://storage.cloud.google.com/stratus_performance_benchmark_staging/main/pr1849_main_be0f53c_bench-3163550627.png)

**Pull request merged**
